apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crypto-app
  name: crypto-app
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-app
  strategy: {}
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
      - image: 377027906194.dkr.ecr.us-east-1.amazonaws.com/crypto-app:latest
        imagePullPolicy: Always
        name: crypto-app
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-service
  labels:
    app: crypto-app
  namespace: development
spec:
  selector:
    app: crypto-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-ingress
  namespace: development 
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/group.name: "crypto-group"
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: crypto-service
              port:
                number: 80